# Setup
url: http://roshanca.com
author: Johnsen
title: Johnsen
subtitle: Life is like a box of chocolates.

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year/:title
# relative_permalinks: true

# Where things are
source: site
destination: ./_site
plugins_dir: ./_plugins

# Markdown Processors
markdown: redcarpet
redcarpet:
  extensions: [autolink, smart, tables, strikethrough, superscript, footnotes]

# Syntax highlighting
highlighter: rouge

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _scss
  style: :compressed

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: johnsen
branch: master
repo: blog
